# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wikidata_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateField()),
                ('left', models.DateField(blank=True)),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Parliament')),
            ],
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('surname_prefix', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('residence', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founded', models.DateField()),
                ('dissolved', models.DateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='partymember',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty'),
        ),
        migrations.AddField(
            model_name='partymember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Person'),
        ),
        migrations.AddField(
            model_name='parliamentmember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.Person'),
        ),
    ]
