# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamentmember',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
