# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wikidata_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='wikidata_url',
            field=models.URLField(blank=True),
        ),
    ]
