# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='joined',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='partymember',
            name='left',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
