# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_auto_20161123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='name_short',
            field=models.CharField(max_length=200),
        ),
    ]
