# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_auto_20160513_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parliament',
            name='wikidata_url',
        ),
        migrations.RemoveField(
            model_name='person',
            name='wikidata_url',
        ),
        migrations.RemoveField(
            model_name='politicalparty',
            name='wikidata_url',
        ),
        migrations.AddField(
            model_name='parliament',
            name='wikidata_uri',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='wikidata_uri',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='wikidata_uri',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
