# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_remove_politicalparty_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='official_website_url',
            field=models.URLField(blank=True),
        ),
    ]
