# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_auto_20160513_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='residence',
        ),
    ]
