# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_politicalparty_current_parliament_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamentmember',
            name='joined',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentmember',
            name='left',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
