# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_remove_person_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parliamentmember',
            name='left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='dissolved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
