# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_auto_20170324_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='current_parliament_seats',
            field=models.IntegerField(default=0),
        ),
    ]
