# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_auto_20160518_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
