# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 00:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_auto_20160513_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='joined',
            field=models.DateField(default=datetime.datetime(2016, 5, 13, 0, 34, 13, 356865, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partymember',
            name='left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
