# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_auto_20170327_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='official_website_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='wikimedia_logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
