# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_auto_20190203_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('name_short', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', max_length=250)),
            ],
        ),
    ]
