# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0008_auto_20160513_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymember',
            name='joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
