# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0005_person_twitter_username'),
        ('parliament', '0006_auto_20170327_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, default='', max_length=1000)),
                ('purpose', models.CharField(blank=True, default='', max_length=1000)),
                ('paid_by', models.CharField(blank=True, default='', max_length=1000)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPersonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parliament_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentMember')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.AddField(
            model_name='travel',
            name='person_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelPersonPosition'),
        ),
        migrations.AlterUniqueTogether(
            name='travelpersonposition',
            unique_together=set([('person', 'date')]),
        ),
    ]
