# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-08 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_auto_20181208_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personposition',
            name='government_member',
        ),
    ]
