# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.CharField(max_length=500)),
                ('raw_type', models.CharField(max_length=200)),
                ('surname_prefix', models.CharField(blank=True, default='', max_length=200)),
                ('source_page_url', models.URLField(blank=True)),
                ('publisher', models.CharField(max_length=200)),
                ('date_published', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
