# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['date_published']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='surname_prefix',
        ),
    ]
