# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_html',
            field=models.CharField(blank=True, max_length=200000),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='publication_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='submitter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
