# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_auto_20160518_1506'),
        ('document', '0002_auto_20160523_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('decision', models.CharField(choices=[('FO', 'For'), ('AG', 'Against')], max_length=2)),
                ('details', models.CharField(blank=True, default='', max_length=2000)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty')),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden')], max_length=3)),
                ('date', models.DateField(blank=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Dossier')),
                ('kamerstuk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Kamerstuk')),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Voting'),
        ),
    ]
