# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_dossier_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='decision',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dossier',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
