# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20160518_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_url',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
