# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20161117_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='result',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden'), ('ONB', 'ONB')], max_length=3),
        ),
    ]
