# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20160825_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_dossier_voting',
            field=models.BooleanField(default=False),
        ),
    ]
