# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20161118_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden'), ('INB', 'In behandeling'), ('ONB', 'ONB')], default='ONB', max_length=3),
        ),
    ]
