# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20160518_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dossier_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
