# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_agenda_agenda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='dossier_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='dossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Dossier'),
        ),
    ]
