# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_dossier_status'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='kamerstuk',
            index_together=set([('id_main', 'id_sub')]),
        ),
    ]
