# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_dossier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kamerstuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_main', models.IntegerField(blank=True, null=True)),
                ('id_sub', models.IntegerField(blank=True, null=True)),
                ('type_short', models.CharField(blank=True, max_length=40)),
                ('type_long', models.CharField(blank=True, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
    ]
