# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20160917_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaitem',
            old_name='dossier_text',
            new_name='item_text',
        ),
    ]
