# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20161123_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_published',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='dossier_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden'), ('INB', 'In behandeling'), ('ONB', 'ONB')], db_index=True, default='ONB', max_length=3),
        ),
        migrations.AlterField(
            model_name='voting',
            name='result',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden'), ('ONB', 'ONB')], db_index=True, max_length=3),
        ),
    ]
