# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_kamerstuk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_id', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kamerstuk',
            options={'verbose_name_plural': 'Kamerstukken'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='dossier_id',
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Dossier'),
        ),
    ]
