# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20160917_1737'),
        ('document', '0007_auto_20160915_2217'),
    ]

    operations = [
    ]
