# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20161123_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='date',
            field=models.DateField(blank=True, db_index=True),
        ),
    ]
