# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_merge_20161014_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamerstuk',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Kamerstuk'),
        ),
    ]
