# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20161123_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_mistake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vote',
            name='decision',
            field=models.CharField(choices=[('FO', 'For'), ('AG', 'Against'), ('NO', 'None')], max_length=2),
        ),
    ]
