# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20161124_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='result',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden'), ('CON', 'Controversieel'), ('ONB', 'Onbekend')], db_index=True, max_length=3),
        ),
    ]
