# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_kamerstuk_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamerstuk',
            name='original',
        ),
        migrations.AddField(
            model_name='kamerstuk',
            name='original_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
