# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20161125_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden'), ('INB', 'In behandeling'), ('CON', 'Controversieel'), ('ONB', 'Onbekend')], db_index=True, default='ONB', max_length=3),
        ),
    ]
