# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20161016_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteindividual',
            name='parliament_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.ParliamentMember'),
        ),
    ]
