# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20161021_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossier',
            options={'ordering': ['-dossier_id']},
        ),
    ]
