# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20161125_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluitenlijst',
            name='commission',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='besluitenlijst',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='besluititem',
            name='title',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='besluititemcase',
            name='decisions',
            field=models.CharField(max_length=7000),
        ),
        migrations.AlterField(
            model_name='besluititemcase',
            name='notes',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='decision',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='vote',
            name='details',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
