# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20161026_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='BesluitenLijst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('commission', models.CharField(max_length=50)),
                ('activity_id', models.CharField(max_length=100)),
                ('date_published', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BesluitItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BesluitItemCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('decisions', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=500)),
                ('related_commissions', models.CharField(max_length=500)),
                ('related_document_ids', models.CharField(max_length=300)),
            ],
        ),
    ]
