# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20161031_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='besluitenlijst',
            options={'ordering': ['-date_published']},
        ),
    ]
