# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20161101_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kamerstuk',
            options={'ordering': ['-document__date_published', '-id_sub'], 'verbose_name_plural': 'Kamerstukken'},
        ),
    ]
