# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0017_auto_20161127_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='besluititemcase',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
