# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20161104_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='categories',
            field=models.ManyToManyField(blank=True, to='document.Category'),
        ),
    ]
