# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20161127_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=2000),
        ),
    ]
