# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_dossier_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteindividual',
            name='person_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='voteparty',
            name='party_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='voteparty',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty'),
        ),
    ]
