# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_auto_20161104_2214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentCategory',
            new_name='CategoryDocument',
        ),
        migrations.RenameModel(
            old_name='DossierCategory',
            new_name='CategoryDossier',
        ),
        migrations.AlterModelOptions(
            name='categorydocument',
            options={'verbose_name': 'Category (document)', 'verbose_name_plural': 'Categories (document)'},
        ),
        migrations.AlterModelOptions(
            name='categorydossier',
            options={'verbose_name': 'Category (dossier)', 'verbose_name_plural': 'Categories (dossier)'},
        ),
    ]
