# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0021_auto_20161214_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteindividual',
            name='parliament_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.ParliamentMember'),
        ),
        migrations.AlterField(
            model_name='voteparty',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parliament.PoliticalParty'),
        ),
    ]
