# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_auto_20161104_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorydocument',
            options={'ordering': ['name'], 'verbose_name': 'Category (document)', 'verbose_name_plural': 'Categories (document)'},
        ),
        migrations.AlterModelOptions(
            name='categorydossier',
            options={'ordering': ['name'], 'verbose_name': 'Category (dossier)', 'verbose_name_plural': 'Categories (dossier)'},
        ),
    ]
