# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0022_auto_20161214_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
