# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_dossier_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
