# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_voting_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kamerstuk',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
