# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_auto_20170223_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antwoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Kamervraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
        migrations.AddField(
            model_name='antwoord',
            name='antwoord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Kamervraag'),
        ),
        migrations.AddField(
            model_name='antwoord',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document'),
        ),
    ]
