# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0027_document_source_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antwoord',
            name='antwoord',
        ),
        migrations.AddField(
            model_name='antwoord',
            name='kamervraag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Kamervraag'),
        ),
        migrations.AddField(
            model_name='antwoord',
            name='vraagnummer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kamervraag',
            name='vraagnummer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
