# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0030_auto_20170307_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antwoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('text', models.CharField(max_length=10000)),
                ('kamerantwoord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Kamerantwoord')),
            ],
        ),
    ]
