# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0031_antwoord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamerantwoord',
            name='kamervraag',
        ),
        migrations.AddField(
            model_name='kamervraag',
            name='kamerantwoord',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Kamerantwoord'),
        ),
    ]
