# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0032_auto_20170307_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamervraag',
            name='receiver',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
