# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0033_kamervraag_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='antwoord',
            name='is_combined',
            field=models.BooleanField(default=False),
        ),
    ]
