# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0037_footnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
