# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0039_auto_20170308_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antwoord',
            options={'ordering': ['nr']},
        ),
        migrations.AlterModelOptions(
            name='vraag',
            options={'ordering': ['nr']},
        ),
    ]
