# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0041_auto_20170308_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitter',
            name='party_slug',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
