# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0042_submitter_party_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwoord',
            name='text',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='vraag',
            name='text',
            field=models.CharField(max_length=50000),
        ),
    ]
