# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0043_auto_20170310_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footnote',
            name='text',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
