# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0044_auto_20170316_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamerantwoord',
            name='vraagnummer',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kamerstuk',
            name='id_main',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='kamerstuk',
            name='id_sub',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='kamerstuk',
            name='original_id',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='kamervraag',
            name='vraagnummer',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='submitter',
            name='party_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
