# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0045_auto_20170324_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antwoord',
            name='nr',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='footnote',
            name='nr',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='vraag',
            name='nr',
            field=models.IntegerField(db_index=True),
        ),
    ]
