# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0047_kamerstuk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamerstuk',
            name='type',
            field=models.CharField(choices=[('Motie', 'Motie'), ('Amendement', 'Amendement'), ('Wetsvoorstel', 'Wetsvoorstel'), ('Verslag', 'Verslag'), ('Nota', 'Nota'), ('Brief', 'Brief'), ('Verslag AO', 'Verslag van een algemeen overleg'), ('Onbekend', 'Onbekend')], db_index=True, default='Onbekend', max_length=30),
        ),
    ]
