# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0048_kamervraagmededeling'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='types',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
