# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0049_document_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossier',
            name='is_active',
        ),
    ]
