# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0050_remove_dossier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, unique=True),
        ),
    ]
