# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0051_auto_20171027_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='kamerstuk_raw_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
