# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0052_auto_20171027_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='source_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
