# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_twitter_username'),
        ('document', '0053_voting_source_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submitter',
            unique_together=set([('person', 'document')]),
        ),
    ]
