# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0054_auto_20171103_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamerstuk',
            name='id_main_extra',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='kamerstuk',
            name='type',
            field=models.CharField(choices=[('Motie', 'Motie'), ('Amendement', 'Amendement'), ('Wetsvoorstel', 'Wetsvoorstel'), ('Verslag', 'Verslag'), ('Nota', 'Nota'), ('Brief', 'Brief'), ('VerslagAlgemeenOverleg', 'Verslag van een algemeen overleg'), ('Onbekend', 'Onbekend')], db_index=True, default='Onbekend', max_length=30),
        ),
    ]
