# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0055_auto_20171123_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='voting',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
