# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0055_auto_20171123_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='kamerstuk',
            name='dossier_ids_related',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
