# Generated by Django 2.2.7 on 2019-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0057_commissiedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='dossier_main_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dossier',
            name='dossier_sub_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dossier',
            unique_together={('dossier_main_id', 'dossier_sub_id')},
        ),
    ]
