# Generated by Django 2.2.7 on 2019-11-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0058_auto_20191129_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamerstuk',
            name='id_main_extra',
        ),
    ]
