# Generated by Django 2.2.7 on 2019-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0059_remove_kamerstuk_id_main_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_html',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
