# Generated by Django 2.2.8 on 2019-12-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0061_voteindividual_person_tk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='besluititem',
            name='besluiten_lijst',
        ),
        migrations.RemoveField(
            model_name='besluititemcase',
            name='besluit_item',
        ),
        migrations.DeleteModel(
            name='BesluitenLijst',
        ),
        migrations.DeleteModel(
            name='BesluitItem',
        ),
        migrations.DeleteModel(
            name='BesluitItemCase',
        ),
    ]
