# Generated by Django 2.2.8 on 2019-12-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0062_auto_20191214_1539_squashed_0070_auto_20191214_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='datetime',
        ),
    ]
