# Generated by Django 2.2.8 on 2019-12-14 15:13

from django.db import migrations, models
import django.db.models.deletion
import tkapi.besluit


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0062_auto_20191214_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='decision',
            new_name='decision_text',
        ),
        migrations.AddField(
            model_name='voting',
            name='tk_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[(tkapi.besluit.BesluitStatus('Besluit'), 'Besluit'), (tkapi.besluit.BesluitStatus('Concept voorstel'), 'Concept voorstel'), (tkapi.besluit.BesluitStatus('Voorstel'), 'Voorstel'), (tkapi.besluit.BesluitStatus('Nog te verwerken besluit'), 'Nog te verwerken besluit')], db_index=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=10000)),
                ('type', models.CharField(blank=True, max_length=10000)),
                ('note', models.CharField(blank=True, max_length=10000)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Dossier')),
            ],
        ),
        migrations.AddField(
            model_name='voting',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Decision'),
        ),
    ]
