# Generated by Django 2.2.8 on 2019-12-19 20:47

from django.db import migrations, models
import django.db.models.deletion
import tkapi.activiteit


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0063_remove_document_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('type', models.CharField(choices=[(tkapi.activiteit.ActiviteitSoort('Aanbieding'), 'Aanbieding'), (tkapi.activiteit.ActiviteitSoort('Afscheid'), 'Afscheid'), (tkapi.activiteit.ActiviteitSoort('Algemeen overleg'), 'Algemeen overleg'), (tkapi.activiteit.ActiviteitSoort('Beëdiging'), 'Beëdiging'), (tkapi.activiteit.ActiviteitSoort('Begrotingsoverleg'), 'Begrotingsoverleg'), (tkapi.activiteit.ActiviteitSoort('Bijzondere procedure'), 'Bijzondere procedure'), (tkapi.activiteit.ActiviteitSoort('Constituerende vergadering'), 'Constituerende vergadering'), (tkapi.activiteit.ActiviteitSoort('Delegatievergadering'), 'Delegatievergadering'), (tkapi.activiteit.ActiviteitSoort('E-mailprocedure'), 'E-mailprocedure'), (tkapi.activiteit.ActiviteitSoort('Gesprek'), 'Gesprek'), (tkapi.activiteit.ActiviteitSoort('Hamerstukken'), 'Hamerstukken'), (tkapi.activiteit.ActiviteitSoort('Herdenking'), 'Herdenking'), (tkapi.activiteit.ActiviteitSoort('Hoorzitting'), 'Hoorzitting'), (tkapi.activiteit.ActiviteitSoort('Hoorzitting / rondetafelgesprek'), 'Hoorzitting / rondetafelgesprek'), (tkapi.activiteit.ActiviteitSoort('Inbreng feitelijke vragen'), 'Inbreng feitelijke vragen'), (tkapi.activiteit.ActiviteitSoort('Inbreng schriftelijk overleg'), 'Inbreng schriftelijk overleg'), (tkapi.activiteit.ActiviteitSoort('Interpellatiedebat'), 'Interpellatiedebat'), (tkapi.activiteit.ActiviteitSoort('Mededelingen'), 'Mededelingen'), (tkapi.activiteit.ActiviteitSoort('Notaoverleg'), 'Notaoverleg'), (tkapi.activiteit.ActiviteitSoort('Ontbijtbijeenkomst Parlement en Wetenschap'), 'Ontbijtbijeenkomst Parlement en Wetenschap'), (tkapi.activiteit.ActiviteitSoort('Opening'), 'Opening'), (tkapi.activiteit.ActiviteitSoort('Overig'), 'Overig'), (tkapi.activiteit.ActiviteitSoort('Petitie'), 'Petitie'), (tkapi.activiteit.ActiviteitSoort('Plenair debat'), 'Plenair debat'), (tkapi.activiteit.ActiviteitSoort('Procedurevergadering'), 'Procedurevergadering'), (tkapi.activiteit.ActiviteitSoort('Regeling van werkzaamheden'), 'Regeling van werkzaamheden'), (tkapi.activiteit.ActiviteitSoort('Rondetafelgesprek'), 'Rondetafelgesprek'), (tkapi.activiteit.ActiviteitSoort('Schriftelijk commentaar algemeen'), 'Schriftelijk commentaar algemeen'), (tkapi.activiteit.ActiviteitSoort('Schriftelijk commentaar gericht'), 'Schriftelijk commentaar gericht'), (tkapi.activiteit.ActiviteitSoort('Sluiting'), 'Sluiting'), (tkapi.activiteit.ActiviteitSoort('Stemmingen'), 'Stemmingen'), (tkapi.activiteit.ActiviteitSoort('Technische briefing'), 'Technische briefing'), (tkapi.activiteit.ActiviteitSoort('Vergadering'), 'Vergadering'), (tkapi.activiteit.ActiviteitSoort('Verklaring'), 'Verklaring'), (tkapi.activiteit.ActiviteitSoort('Vragenuur'), 'Vragenuur'), (tkapi.activiteit.ActiviteitSoort('Werkbezoek'), 'Werkbezoek'), (tkapi.activiteit.ActiviteitSoort('Wetgevingsoverleg'), 'Wetgevingsoverleg'), (tkapi.activiteit.ActiviteitSoort('Inbreng verslag (wetsvoorstel)'), 'Inbreng verslag (wetsvoorstel)')], db_index=True, max_length=200)),
                ('status', models.CharField(choices=[(tkapi.activiteit.ActiviteitStatus('Geannuleerd'), 'Geannuleerd'), (tkapi.activiteit.ActiviteitStatus('Gepland'), 'Gepland'), (tkapi.activiteit.ActiviteitStatus('Uitgevoerd'), 'Uitgevoerd'), (tkapi.activiteit.ActiviteitStatus('Verplaatst'), 'Verplaatst')], db_index=True, max_length=200)),
                ('datetime', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('begin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=10000)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Dossier')),
                ('kamerstuk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Kamerstuk')),
            ],
        ),
    ]
