# Generated by Django 2.2.8 on 2019-12-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0063_auto_20191214_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
