# Generated by Django 2.2.8 on 2020-04-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0063_remove_document_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamervraag',
            name='receiver',
        ),
    ]
