# Generated by Django 2.2.8 on 2019-12-14 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0064_decision_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='decision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Decision'),
        ),
    ]
