# Generated by Django 2.2.8 on 2020-04-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0064_remove_kamervraag_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitter',
            name='type',
            field=models.CharField(choices=[('submitter', 'submitter'), ('receiver', 'receiver')], db_index=True, default='submitter', max_length=30),
        ),
    ]
