# Generated by Django 2.2.28 on 2025-11-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20200501_1504'),
        ('document', '0065_submitter_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submitter',
            unique_together={('person', 'document', 'type')},
        ),
    ]
