# Generated by Django 2.2.8 on 2019-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0066_decision_kamerstuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
