# Generated by Django 2.2.8 on 2019-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0067_auto_20191214_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_published',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
