# Generated by Django 2.2.8 on 2019-12-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0069_auto_20191214_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AddField(
            model_name='document',
            name='datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
