# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0005_person_twitter_username'),
        ('parliament', '0003_auto_20161126_2342'),
        ('document', '0024_voting_is_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsVotingSubmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Voting')),
            ],
        ),
    ]
