# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20161228_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KVT', 'Kamervraag vs Time'), ('KRTH', 'Kamervraag reply time histogram'), ('KRT2D', 'Kamervraag reply time 2D histogram')], db_index=True, default='KVT', max_length=10)),
                ('html', models.TextField()),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-datetime_updated'],
            },
        ),
    ]
