# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.CharField(choices=[('KVT', 'Kamervraag vs Time'), ('KRTH', 'Kamervraag reply time histogram'), ('KRT2D', 'Kamervraag reply time 2D histogram')], db_index=True, default='KVT', max_length=10, unique=True),
        ),
    ]
