# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_auto_20170327_0914'),
        ('stats', '0007_auto_20170817_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatsPerParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats', models.IntegerField(default=0)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty')),
            ],
        ),
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.CharField(choices=[('KVT', 'Kamervraag vs time'), ('KVTP', 'Kamervraag vs time per party'), ('KRTH', 'Kamervraag reply time histogram'), ('KRT2D', 'Kamervraag reply time 2D histogram'), ('KRTPP', 'Kamervraag reply time per party'), ('KRTPY', 'Kamervraag reply time per year'), ('KRTPM', 'Kamervraag reply time per ministerie'), ('KRTPMP', 'Kamervraag reply time per ministerie bewindspersoon'), ('KRTPPO', 'Kamervraag reply time per minister of staatssecretaris')], db_index=True, default='KVT', max_length=10, unique=True),
        ),
    ]
