# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0049_document_types'),
        ('stats', '0008_auto_20170818_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotKamervraagOnderwerp',
            fields=[
                ('plot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stats.Plot')),
                ('y_scale_type', models.CharField(choices=[('DFMRA', 'Difference from the mean number of kamervragen per category, relative to total kamervragen')], db_index=True, default='DFMRA', max_length=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.CategoryDocument')),
            ],
            bases=('stats.plot',),
        ),
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.CharField(choices=[('KVT', 'Kamervraag vs time'), ('KVTP', 'Kamervraag vs time per party'), ('KVTPS', 'Kamervraag vs time per party seat'), ('KVTPCL', 'Kamervraag vs time per category'), ('KRTH', 'Kamervraag reply time histogram'), ('KRT2D', 'Kamervraag reply time 2D histogram'), ('KRTPP', 'Kamervraag reply time per party'), ('KRTPY', 'Kamervraag reply time per year'), ('KRTPM', 'Kamervraag reply time per ministerie'), ('KRTPMP', 'Kamervraag reply time per ministerie bewindspersoon'), ('KRTPPO', 'Kamervraag reply time per minister of staatssecretaris'), ('SPPVT', 'Seats per party vs time')], db_index=True, default='KVT', max_length=10),
        ),
    ]
