# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20170824_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotkamervraagonderwerp',
            name='n_kamervragen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
