# Generated by Django 2.2.12 on 2020-05-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20171026_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='type',
            field=models.CharField(choices=[('KVT', 'Kamervraag vs time'), ('KVTP', 'Kamervraag vs time per party'), ('KVTPS', 'Kamervraag vs time per party seat'), ('KRTH', 'Kamervraag reply time histogram'), ('KRT2D', 'Kamervraag reply time 2D histogram'), ('KRTPP', 'Kamervraag reply time per party'), ('KRTPY', 'Kamervraag reply time per year'), ('SPPVT', 'Seats per party vs time')], db_index=True, default='KVT', max_length=10, unique=True),
        ),
    ]
