# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(choices=[('AM', 'Amendement'), ('MO', 'Motie'), ('WV', 'Wetsvoorstel')], max_length=2)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('document_url', models.URLField(blank=True, default='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PartyMember')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('decision', models.CharField(choices=[('FO', 'Voor'), ('AG', 'Tegen')], max_length=2)),
                ('details', models.CharField(blank=True, default='', max_length=2000)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Bill')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty')),
            ],
        ),
    ]
