# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(choices=[('AM', 'Amendement'), ('MO', 'Motie'), ('WV', 'Wetsvoorstel')], max_length=2)),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('document_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('surname_prefix', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Man'), ('F', 'Vrouw')], max_length=1)),
                ('residence', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seats', models.IntegerField()),
                ('url', models.URLField(blank=True, default='')),
                ('icon_url', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seats', models.IntegerField()),
                ('decision', models.CharField(choices=[('FO', 'Voor'), ('AG', 'Tegen')], max_length=2)),
                ('details', models.CharField(blank=True, default='', max_length=2000)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Bill')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Party')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Party'),
        ),
        migrations.AddField(
            model_name='bill',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.Member'),
        ),
    ]
