# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20160523_1544'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken')], max_length=3)),
                ('date', models.DateField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='bill',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.AddField(
            model_name='vote',
            name='voting',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='voting.Voting'),
            preserve_default=False,
        ),
    ]
