# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20160523_1544'),
        ('voting', '0002_auto_20160825_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='document',
        ),
        migrations.AddField(
            model_name='voting',
            name='kamerstuk',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='document.Kamerstuk'),
            preserve_default=False,
        ),
    ]
