# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_member_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='party',
        ),
        migrations.AlterField(
            model_name='bill',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PartyMember'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parliament.PoliticalParty'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
    ]
