# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20160825_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='result',
            field=models.CharField(choices=[('AAN', 'Aangenomen'), ('VER', 'Verworpen'), ('ING', 'Ingetrokken'), ('AGH', 'Aangehouden')], max_length=3),
        ),
    ]
