# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20160825_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='kamerstuk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Kamerstuk'),
        ),
    ]
