# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20160825_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='decision',
            field=models.CharField(choices=[('FO', 'For'), ('AG', 'Against')], max_length=2),
        ),
    ]
