# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='forename',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='initials',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname_prefix',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
