# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wikimedia_image_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
