# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20161123_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wikimedia_image_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
