# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='parlement_and_politiek_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
