# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20161125_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
