# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='', max_length=250),
        ),
    ]
