# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20161125_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
