# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_twitter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='wikimedia_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='wikipedia_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
