# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20161029_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wikipedia_url',
            field=models.URLField(blank=True),
        ),
    ]
