# Generated by Django 2.2.7 on 2019-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20190203_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tk_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='parlement_and_politiek_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='wikidata_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
