# Generated by Django 2.2.8 on 2019-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20191205_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
