# Generated by Django 2.2.12 on 2020-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_person_datetime_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='forename',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
    ]
