# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_formed', models.DateField()),
                ('date_dissolved', models.DateField(blank=True, null=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('MIN', 'Minister'), ('MWP', 'Minister zonder portefeuille'), ('SOS', 'Staatssecretaris'), ('PMI', 'Minister-president'), ('DPM', 'Viceminister-president')], max_length=3)),
                ('extra_info', models.CharField(blank=True, max_length=200)),
                ('government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='government.Government')),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.Government')),
            ],
        ),
        migrations.AddField(
            model_name='governmentposition',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='government.Ministry'),
        ),
        migrations.AddField(
            model_name='governmentmember',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.GovernmentPosition'),
        ),
    ]
