# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentposition',
            name='extra_info',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
