# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_initials'),
        ('government', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('MIN', 'Minister'), ('SOS', 'Secretary of State'), ('PMI', 'Prime Minister'), ('DPM', 'Deputy Prime Minister')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.Government')),
            ],
        ),
        migrations.AddField(
            model_name='governmentposition',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.Ministry'),
        ),
        migrations.AddField(
            model_name='governmentmember',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.GovernmentPosition'),
        ),
    ]
