# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_governmentposition_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentposition',
            name='position',
            field=models.CharField(choices=[('MIN', 'Minister'), ('MWP', 'Minister zonder portefeuille'), ('SOS', 'Staatssecretaris'), ('PMI', 'Minister-president'), ('DPM', 'Viceminister-president')], max_length=3),
        ),
    ]
