# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20161123_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='government',
            options={'ordering': ['-date_formed']},
        ),
    ]
