# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0002_auto_20161019_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentposition',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='government.Ministry'),
        ),
    ]
