# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0004_auto_20161019_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentposition',
            name='government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='government.Government'),
        ),
    ]
