# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_governmentposition_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='date_dissolved',
            field=models.DateField(blank=True, null=True),
        ),
    ]
